jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8083
   servlet:
      context-path: /gestion-personas
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/gestionPersonas?autoReconnect=true&useSSL=false
      username: root
      password: ENC(AAtsl8e4mN7lqlBaNjowXA==)
      hikari:
         poolName: pool
